# set the working directory from script input
work_dir=$1
cd $work_dir

# loop over every .fa file in the WD and replace 'user sequence' with the sequence name
for file in $(ls *.fa); do 
	# get the sequence name from the file name
	seq_name=$(basename $file .fa)
	echo $seq_name
	# replace sequence headers
	sed -i -e "s/user sequence/${seq_name}/g" $file
done

# remove all .fa-e files generated by SED
rm *.fa-e

# generate a new file for the multifasta
multifasta=$(echo seq_consensus-$(echo $(basename $(ls *.fa | head -n 1) .fa) | cut -d "-" -f 2).fasta)
echo > $multifasta

# concat all fasta files in the WD into a multifasta
for file in $(ls *.fa); do 
	cat $file >> $multifasta
	echo >> $multifasta
done
